### ISSUE TITLE
Configure Networks

### ISSUE THREAD

**Issue by puck3000** [enovatedesign/vagrant-craft#1]
Hello
After following the steps in the readme i cannot reach the server on localhost:8080. After running vagrant up terminal gives me this warning:

```
Vagrant attempted to execute the capability 'configure_networks'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
```

any idea where i went wrong? 

thank you for your time

**Comment by mtwalsh** [comment]
Hi,

I'm afraid we're no longer using Vagrant on a regular basis so I'm not best equipped to help.  For what it's worth it seems like your issue is more of a Vagrant issue than an issue with the code in this repo.  There's a few solutions suggested on this issue:

https://github.com/mitchellh/vagrant/issues/6426
